In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

In [5]:
df=pd.DataFrame(pd.read_csv(r"used_cars_data.csv"))

In [6]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [259]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [260]:
df.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [261]:
df.describe()

             S.No.         Year  Kilometers_Driven        Seats        Price
count  7253.000000  7253.000000       7.253000e+03  7200.000000  6019.000000
mean   3626.000000  2013.365366       5.869906e+04     5.279722     9.479468
std    2093.905084     3.254421       8.442772e+04     0.811660    11.187917
min       0.000000  1996.000000       1.710000e+02     0.000000     0.440000
25%    1813.000000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3626.000000  2014.000000       5.341600e+04     5.000000     5.640000
75%    5439.000000  2016.000000       7.300000e+04     5.000000     9.950000
max    7252.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [262]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7248    False
7249    False
7250    False
7251    False
7252    False
Length: 7253, dtype: bool

In [263]:
df.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [264]:
df["Engine_CC"] = pd.to_numeric(df["Engine"].str.split().str[0])
df["Engine_CC"] = df["Engine_CC"].fillna(df["Engine_CC"].mean())

In [265]:
print(df["Engine_CC"].dtype)

float64

In [266]:
df["Power_bhp"] = df["Power"].str.split().str[0]
df["Power_bhp"] = df["Power_bhp"].replace("null", np.nan)
df["Power_bhp"] = df["Power_bhp"].astype(float)
df["Power_bhp"] = df["Power_bhp"].fillna(df["Power_bhp"].mean())

In [267]:
print(df["Power_bhp"].dtype)

float64

In [268]:
df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price', 'Engine_CC', 'Power_bhp'],
      dtype='object')

In [269]:
df["Seats"] = df["Seats"].fillna(5)

In [270]:
df["Seats"].isnull().sum()

0

In [271]:
df = df.dropna(subset=["Price"])

In [272]:
df.drop(["S.No.", "Name", "Engine", "Power","New_Price"],axis=1,inplace=True)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_27116\786968931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["S.No.", "Name", "Engine", "Power","New_Price"],axis=1,inplace=True)

In [273]:
df.columns

Index(['Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Transmission',
       'Owner_Type', 'Mileage', 'Seats', 'Price', 'Engine_CC', 'Power_bhp'],
      dtype='object')

In [274]:
df = pd.get_dummies(df,columns=["Fuel_Type", "Transmission", "Owner_Type","Location"],dtype=int)

In [279]:
df["Mileage"] = df["Mileage"].str.split().str[0]
df["Mileage"] = pd.to_numeric(df["Mileage"], errors="coerce")
df["Mileage"] = df["Mileage"].fillna(df["Mileage"].mean())

In [280]:
print(df.isnull().sum().sum())

0

In [7]:
X = df.drop("Price", axis=1)

y = df["Price"]

In [286]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [296]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [297]:
prediction = model.predict(X_test)

In [298]:
X_test

,Year,Kilometers_Driven,Mileage,Seats,Engine_CC,Power_bhp,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,...,Location_Bangalore,Location_Chennai,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune
2868,2013,69000,23.40,5.0,1248.00000,74.000000,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
5924,2017,26741,15.40,7.0,1997.00000,120.000000,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3764,2014,86000,15.10,7.0,2179.00000,140.000000,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
4144,2016,52000,25.00,5.0,1396.00000,69.010000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2780,2009,100000,0.00,5.0,1616.57347,112.765214,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5926,2000,78000,16.10,4.0,796.00000,37.000000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4216,2015,43053,18.90,5.0,998.00000,67.100000,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1351,2015,44620,20.73,5.0,1373.00000,91.100000,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4603,2019,21112,15.10,5.0,1196.00000,73.000000,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5668,2007,68000,17.80,5.0,1399.00000,68.000000,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0

In [299]:
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(r2)
print(mse)
print(rmse)

0.38078472914435035
76.20031660402653
8.729279271739822