In [28]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [29]:
df = pd.read_csv("Kaggle_Ecommerce Data.csv")

In [140]:
df

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivered_date,region,returned,request_date,return_reason,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,23/12/2023,27/12/2023,West,No,NaN,NaN,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,3/4/2025,9/4/2025,South,No,NaN,NaN,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,8/10/2024,12/10/2024,North,No,NaN,NaN,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,14/9/2024,20/9/2024,South,No,NaN,NaN,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,21/12/2024,27/12/2024,East,No,NaN,NaN,13.88,2.74,1.15,39,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34495,O134495,C13553,P231412,Fashion,10.44,0.20,1,Debit Card,13/8/2025,16/8/2025,North,No,NaN,NaN,8.35,3.04,-0.12,23,Female
34496,O134496,C11349,P218266,Beauty,4.79,0.10,5,Debit Card,4/12/2023,10/12/2023,South,Yes,27/12/2023,No longer needed,21.56,3.37,6.33,61,Female
34497,O134497,C12986,P204345,Electronics,323.64,0.00,5,Credit Card,1/2/2025,7/2/2025,East,No,NaN,NaN,1618.20,12.18,182.00,41,Female
34498,O134498,C17196,P217644,Home,23.09,0.05,1,Credit Card,27/3/2024,2/4/2024,East,No,NaN,NaN,21.94,5.61,0.53,27,Female
34499,O134499,C13330,P207047,Home,76.84,0.00,1,Debit Card,11/9/2025,17/9/2025,East,No,NaN,NaN,76.84,7.57,13.95,19,Male

In [141]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivered_date,region,returned,request_date,return_reason,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,23/12/2023,27/12/2023,West,No,NaN,NaN,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,3/4/2025,9/4/2025,South,No,NaN,NaN,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,8/10/2024,12/10/2024,North,No,NaN,NaN,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,14/9/2024,20/9/2024,South,No,NaN,NaN,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,21/12/2024,27/12/2024,East,No,NaN,NaN,13.88,2.74,1.15,39,Male

In [142]:
df.tail()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivered_date,region,returned,request_date,return_reason,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
34495,O134495,C13553,P231412,Fashion,10.44,0.20,1,Debit Card,13/8/2025,16/8/2025,North,No,NaN,NaN,8.35,3.04,-0.12,23,Female
34496,O134496,C11349,P218266,Beauty,4.79,0.10,5,Debit Card,4/12/2023,10/12/2023,South,Yes,27/12/2023,No longer needed,21.56,3.37,6.33,61,Female
34497,O134497,C12986,P204345,Electronics,323.64,0.00,5,Credit Card,1/2/2025,7/2/2025,East,No,NaN,NaN,1618.20,12.18,182.00,41,Female
34498,O134498,C17196,P217644,Home,23.09,0.05,1,Credit Card,27/3/2024,2/4/2024,East,No,NaN,NaN,21.94,5.61,0.53,27,Female
34499,O134499,C13330,P207047,Home,76.84,0.00,1,Debit Card,11/9/2025,17/9/2025,East,No,NaN,NaN,76.84,7.57,13.95,19,Male

In [141]:
df.isnull().sum()

order_id               0
customer_id            0
product_id             0
category               0
price                  0
discount               0
quantity               0
payment_method         0
order_date             0
delivered_date         0
region                 0
returned               0
request_date       32597
return_reason      32597
total_amount           0
shipping_cost          0
profit_margin          0
customer_age           0
customer_gender        0
dtype: int64

In [142]:
df.describe()

,price,discount,quantity,total_amount,shipping_cost,profit_margin,customer_age
count,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000
mean,119.391632,0.049291,1.490725,170.008494,6.152120,28.116505,43.474377
std,195.620477,0.069894,0.932270,357.503014,2.389539,53.352947,14.980682
min,1.010000,0.000000,1.000000,0.820000,0.000000,-6.200000,18.000000
25%,16.690000,0.000000,1.000000,19.710000,4.420000,1.500000,31.000000
50%,45.660000,0.000000,1.000000,56.820000,6.090000,10.550000,43.000000
75%,130.950000,0.100000,2.000000,168.530000,7.830000,33.132500,56.000000
max,2930.470000,0.300000,5.000000,12931.800000,15.650000,1536.170000,69.000000

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         34500 non-null  object
 1   customer_id      34500 non-null  object
 2   product_id       34500 non-null  object
 3   category         34500 non-null  object
 4   price            34500 non-null  float64
 5   discount         34500 non-null  float64
 6   quantity         34500 non-null  int64
 7   payment_method   34500 non-null  object
 8   order_date       34500 non-null  object
 9   delivered_date   34500 non-null  object
 10  region           34500 non-null  object
 11  returned         34500 non-null  object
 12  request_date     1903 non-null   object
 13  return_reason    1903 non-null   object
 14  total_amount     34500 non-null  float64
 15  shipping_cost    34500 non-null  float64
 16  profit_margin    34500 non-null  float64
 17  customer_age     34500 non-null  int64
 18  customer_gender  34500 non-null  object
dtypes: float64(5), int64(2), object(12)
memory usage: 5.0+ MB

In [144]:
df.shape

(34500, 19)

In [145]:
df.columns

Index(['order_id', 'customer_id', 'product_id', 'category', 'price',
       'discount', 'quantity', 'payment_method', 'order_date',
       'delivered_date', 'region', 'returned', 'request_date', 'return_reason',
       'total_amount', 'shipping_cost', 'profit_margin', 'customer_age',
       'customer_gender'],
      dtype='object')

In [146]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
34495    False
34496    False
34497    False
34498    False
34499    False
Length: 34500, dtype: bool

In [147]:
df.dtypes

order_id            object
customer_id         object
product_id          object
category            object
price              float64
discount           float64
quantity             int64
payment_method      object
order_date          object
delivered_date      object
region              object
returned            object
request_date        object
return_reason       object
total_amount       float64
shipping_cost      float64
profit_margin      float64
customer_age         int64
customer_gender     object
dtype: object

In [30]:
df = df.drop(columns=[
    "order_id",
    "customer_id",
    "product_id",
    "order_date",
    "delivered_date",
    "request_date",
    "return_reason"
])

In [31]:
df["returned"] = df["returned"].map({"Yes": 1,"No": 0})

In [38]:
X = df.drop("returned", axis=1)
y = df["returned"]

In [33]:
df= pd.get_dummies(df,columns=["category","payment_method","region","customer_gender"],drop_first=True,dtype=int)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   price                       34500 non-null  float64
 1   discount                    34500 non-null  float64
 2   quantity                    34500 non-null  int64
 3   returned                    34500 non-null  int64
 4   total_amount                34500 non-null  float64
 5   shipping_cost               34500 non-null  float64
 6   profit_margin               34500 non-null  float64
 7   customer_age                34500 non-null  int64
 8   category_Electronics        34500 non-null  int32
 9   category_Fashion            34500 non-null  int32
 10  category_Grocery            34500 non-null  int32
 11  category_Home               34500 non-null  int32
 12  category_Sports             34500 non-null  int32
 13  category_Toys               34500 non-null  int32
 14  payment_method_Credit Card  34500 non-null  int32
 15  payment_method_Debit Card   34500 non-null  int32
 16  payment_method_PayPal       34500 non-null  int32
 17  payment_method_UPI          34500 non-null  int32
 18  payment_method_Wallet       34500 non-null  int32
 19  region_East                 34500 non-null  int32
 20  region_North                34500 non-null  int32
 21  region_South                34500 non-null  int32
 22  region_West                 34500 non-null  int32
 23  customer_gender_Male        34500 non-null  int32
 24  customer_gender_Other       34500 non-null  int32
dtypes: float64(5), int32(17), int64(3)
memory usage: 4.3 MB

In [37]:
print(df.select_dtypes(include="object").columns)

Index([], dtype='object')

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [40]:
model = LogisticRegression()
  
model.fit(X_train, y_train)

C:\Users\Shivam shrivastav\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [41]:
y_pred = model.predict(X_test)

In [42]:
accuracy = accuracy_score(y_test,y_pred)

print("Accuracy :",accuracy)

Accuracy : 0.9476811594202899