In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [34]:
df=pd.DataFrame(pd.read_csv(r"used_cars_data.csv"))

In [35]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [36]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [37]:
df.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [38]:
df.describe()

             S.No.         Year  Kilometers_Driven        Seats        Price
count  7253.000000  7253.000000       7.253000e+03  7200.000000  6019.000000
mean   3626.000000  2013.365366       5.869906e+04     5.279722     9.479468
std    2093.905084     3.254421       8.442772e+04     0.811660    11.187917
min       0.000000  1996.000000       1.710000e+02     0.000000     0.440000
25%    1813.000000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3626.000000  2014.000000       5.341600e+04     5.000000     5.640000
75%    5439.000000  2016.000000       7.300000e+04     5.000000     9.950000
max    7252.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [39]:
df.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [40]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7248    False
7249    False
7250    False
7251    False
7252    False
Length: 7253, dtype: bool

In [41]:
df.shape

(7253, 14)

In [42]:
df
df.drop("Mileage",axis=1,inplace=True)

In [43]:
df.drop("New_Price",axis=1,inplace=True)

In [44]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,998 CC,58.16 bhp,5.0,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1582 CC,126.2 bhp,5.0,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,1199 CC,88.7 bhp,5.0,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,1248 CC,88.76 bhp,7.0,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,140.8 bhp,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,NaN

In [45]:
df["Price"]=df["Price"].fillna(df["Price"].mean())

In [46]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,998 CC,58.16 bhp,5.0,1.750000
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1582 CC,126.2 bhp,5.0,12.500000
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,1199 CC,88.7 bhp,5.0,4.500000
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,1248 CC,88.76 bhp,7.0,6.000000
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,140.8 bhp,5.0,17.740000
...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,9.479468
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,9.479468
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,9.479468
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,9.479468
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,9.479468

In [47]:
df["Engine_CC"] = df["Engine"].str.split().str[0].astype(float)
df["Engine_CC"] = df["Engine_CC"].fillna(df["Engine_CC"].mean())

In [48]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Price,Engine_CC
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,998 CC,58.16 bhp,5.0,1.750000,998.0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1582 CC,126.2 bhp,5.0,12.500000,1582.0
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,1199 CC,88.7 bhp,5.0,4.500000,1199.0
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,1248 CC,88.76 bhp,7.0,6.000000,1248.0
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,140.8 bhp,5.0,17.740000,1968.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,9.479468,1598.0
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,9.479468,1197.0
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,9.479468,1461.0
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,9.479468,1197.0
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,9.479468,2148.0

In [49]:
df["Power_bhp"] = ( df["Power"].str.split().str[0].replace("null", np.nan).astype(float))
df["Power_bhp"] = df["Power_bhp"].fillna(df["Power_bhp"].mean())

In [50]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Price,Engine_CC,Power_bhp
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,998 CC,58.16 bhp,5.0,1.750000,998.0,58.16
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1582 CC,126.2 bhp,5.0,12.500000,1582.0,126.20
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,1199 CC,88.7 bhp,5.0,4.500000,1199.0,88.70
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,1248 CC,88.76 bhp,7.0,6.000000,1248.0,88.76
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,140.8 bhp,5.0,17.740000,1968.0,140.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,9.479468,1598.0,103.60
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,9.479468,1461.0,63.10
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,9.479468,2148.0,170.00

In [56]:
df.loc[df["Seats"]<5,"Seats"]=5
#df["Seats"] = df["Seats"].fillna().mode()
df["Seats"] = df["Seats"].fillna(df["Seats"].mode())

In [81]:
df

,S.No.,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Price,Engine_CC,Power_bhp,category
0,0,Mumbai,2010,72000,CNG,Manual,First,998 CC,58.16 bhp,5.0,1.750000,998.0,58.16,Cheap
1,1,Pune,2015,41000,Diesel,Manual,First,1582 CC,126.2 bhp,5.0,12.500000,1582.0,126.20,Expensive
2,2,Chennai,2011,46000,Petrol,Manual,First,1199 CC,88.7 bhp,5.0,4.500000,1199.0,88.70,Cheap
3,3,Chennai,2012,87000,Diesel,Manual,First,1248 CC,88.76 bhp,7.0,6.000000,1248.0,88.76,Moderate
4,4,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,140.8 bhp,5.0,17.740000,1968.0,140.80,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,9.479468,1598.0,103.60,Moderate
7249,7249,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,Moderate
7250,7250,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,9.479468,1461.0,63.10,Moderate
7251,7251,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,Moderate
7252,7252,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,9.479468,2148.0,170.00,Moderate

In [82]:
df.isnull().sum()

S.No.                 0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Engine               46
Power                46
Seats                 0
Price                 0
Engine_CC             0
Power_bhp             0
category              0
dtype: int64

In [83]:
df.describe()

,S.No.,Year,Kilometers_Driven,Seats,Price,Engine_CC,Power_bhp
count,7253.000000,7253.000000,7.253000e+03,7253.000000,7253.000000,7253.000000,7253.000000
mean,3626.000000,2013.365366,5.869906e+04,5.302220,9.479468,1616.573470,112.765214
std,2093.905084,3.254421,8.442772e+04,0.773379,10.191695,593.394164,52.844178
min,0.000000,1996.000000,1.710000e+02,5.000000,0.440000,72.000000,34.200000
25%,1813.000000,2011.000000,3.400000e+04,5.000000,3.850000,1198.000000,77.000000
50%,3626.000000,2014.000000,5.341600e+04,5.000000,6.750000,1493.000000,98.600000
75%,5439.000000,2016.000000,7.300000e+04,5.000000,9.479468,1968.000000,138.030000
max,7252.000000,2019.000000,6.500000e+06,10.000000,160.000000,5998.000000,616.000000

In [84]:
df = pd.get_dummies(df,columns=["Fuel_Type", "Transmission", "Owner_Type"],dtype=int)

In [85]:
df

,S.No.,Location,Year,Kilometers_Driven,Engine,Power,Seats,Price,Engine_CC,Power_bhp,...,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Mumbai,2010,72000,998 CC,58.16 bhp,5.0,1.750000,998.0,58.16,...,0,0,0,0,0,1,1,0,0,0
1,1,Pune,2015,41000,1582 CC,126.2 bhp,5.0,12.500000,1582.0,126.20,...,1,0,0,0,0,1,1,0,0,0
2,2,Chennai,2011,46000,1199 CC,88.7 bhp,5.0,4.500000,1199.0,88.70,...,0,0,0,1,0,1,1,0,0,0
3,3,Chennai,2012,87000,1248 CC,88.76 bhp,7.0,6.000000,1248.0,88.76,...,1,0,0,0,0,1,1,0,0,0
4,4,Coimbatore,2013,40670,1968 CC,140.8 bhp,5.0,17.740000,1968.0,140.80,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Hyderabad,2011,89411,1598 CC,103.6 bhp,5.0,9.479468,1598.0,103.60,...,1,0,0,0,0,1,1,0,0,0
7249,7249,Mumbai,2015,59000,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,...,0,0,0,1,1,0,1,0,0,0
7250,7250,Kolkata,2012,28000,1461 CC,63.1 bhp,5.0,9.479468,1461.0,63.10,...,1,0,0,0,0,1,1,0,0,0
7251,7251,Pune,2013,52262,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,...,0,0,0,1,1,0,0,0,0,1
7252,7252,Kochi,2014,72443,2148 CC,170 bhp,5.0,9.479468,2148.0,170.00,...,1,0,0,0,1,0,1,0,0,0

In [86]:
df.isnull().sum()

S.No.                         0
Location                      0
Year                          0
Kilometers_Driven             0
Engine                       46
Power                        46
Seats                         0
Price                         0
Engine_CC                     0
Power_bhp                     0
category                      0
Fuel_Type_CNG                 0
Fuel_Type_Diesel              0
Fuel_Type_Electric            0
Fuel_Type_LPG                 0
Fuel_Type_Petrol              0
Transmission_Automatic        0
Transmission_Manual           0
Owner_Type_First              0
Owner_Type_Fourth & Above     0
Owner_Type_Second             0
Owner_Type_Third              0
dtype: int64

In [87]:
df

,S.No.,Location,Year,Kilometers_Driven,Engine,Power,Seats,Price,Engine_CC,Power_bhp,...,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Mumbai,2010,72000,998 CC,58.16 bhp,5.0,1.750000,998.0,58.16,...,0,0,0,0,0,1,1,0,0,0
1,1,Pune,2015,41000,1582 CC,126.2 bhp,5.0,12.500000,1582.0,126.20,...,1,0,0,0,0,1,1,0,0,0
2,2,Chennai,2011,46000,1199 CC,88.7 bhp,5.0,4.500000,1199.0,88.70,...,0,0,0,1,0,1,1,0,0,0
3,3,Chennai,2012,87000,1248 CC,88.76 bhp,7.0,6.000000,1248.0,88.76,...,1,0,0,0,0,1,1,0,0,0
4,4,Coimbatore,2013,40670,1968 CC,140.8 bhp,5.0,17.740000,1968.0,140.80,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Hyderabad,2011,89411,1598 CC,103.6 bhp,5.0,9.479468,1598.0,103.60,...,1,0,0,0,0,1,1,0,0,0
7249,7249,Mumbai,2015,59000,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,...,0,0,0,1,1,0,1,0,0,0
7250,7250,Kolkata,2012,28000,1461 CC,63.1 bhp,5.0,9.479468,1461.0,63.10,...,1,0,0,0,0,1,1,0,0,0
7251,7251,Pune,2013,52262,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,...,0,0,0,1,1,0,0,0,0,1
7252,7252,Kochi,2014,72443,2148 CC,170 bhp,5.0,9.479468,2148.0,170.00,...,1,0,0,0,1,0,1,0,0,0

In [88]:
df.head()

,S.No.,Location,Year,Kilometers_Driven,Engine,Power,Seats,Price,Engine_CC,Power_bhp,...,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Mumbai,2010,72000,998 CC,58.16 bhp,5.0,1.75,998.0,58.16,...,0,0,0,0,0,1,1,0,0,0
1,1,Pune,2015,41000,1582 CC,126.2 bhp,5.0,12.50,1582.0,126.20,...,1,0,0,0,0,1,1,0,0,0
2,2,Chennai,2011,46000,1199 CC,88.7 bhp,5.0,4.50,1199.0,88.70,...,0,0,0,1,0,1,1,0,0,0
3,3,Chennai,2012,87000,1248 CC,88.76 bhp,7.0,6.00,1248.0,88.76,...,1,0,0,0,0,1,1,0,0,0
4,4,Coimbatore,2013,40670,1968 CC,140.8 bhp,5.0,17.74,1968.0,140.80,...,1,0,0,0,1,0,0,0,1,0

In [89]:
df["category"]=pd.qcut(df["Price"],q=3,labels=["Cheap","Moderate","Expensive"])

In [90]:
df["category"]

0           Cheap
1       Expensive
2           Cheap
3        Moderate
4       Expensive
          ...
7248     Moderate
7249     Moderate
7250     Moderate
7251     Moderate
7252     Moderate
Name: category, Length: 7253, dtype: category
Categories (3, object): ['Cheap' < 'Moderate' < 'Expensive']

In [91]:
df["category"].value_counts()

category
Moderate     3242
Cheap        2422
Expensive    1589
Name: count, dtype: int64

In [92]:
sp=StratifiedShuffleSplit(n_splits=1,test_size=0.3)

In [93]:
for train_idx,test_idx in sp.split(df.drop(columns="Price",axis=1).copy(),df["category"]):
    train_df=df.loc[train_idx]
    test_df=df.loc[test_idx]

In [94]:
train_df.drop(columns="category",inplace=True)

In [95]:
test_df.drop(columns="category",inplace=True)

In [96]:
train_df.head()

,S.No.,Location,Year,Kilometers_Driven,Engine,Power,Seats,Price,Engine_CC,Power_bhp,...,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
4217,4217,Ahmedabad,2014,75000,1498 CC,98.6 bhp,5.0,6.00,1498.0,98.6,...,1,0,0,0,0,1,1,0,0,0
811,811,Chennai,2015,65000,1498 CC,98.6 bhp,7.0,5.50,1498.0,98.6,...,1,0,0,0,0,1,1,0,0,0
1538,1538,Chennai,2015,21000,796 CC,47.3 bhp,5.0,2.79,796.0,47.3,...,0,0,0,1,0,1,1,0,0,0
5981,5981,Mumbai,2017,6000,1197 CC,83.1 bhp,5.0,7.50,1197.0,83.1,...,0,0,0,1,0,1,1,0,0,0
1534,1534,Coimbatore,2019,23882,1497 CC,117.3 bhp,5.0,11.87,1497.0,117.3,...,0,0,0,1,0,1,1,0,0,0

In [97]:
X_train=train_df.drop(columns="Price",axis=1).copy()
X_test=test_df.drop(columns="Price",axis=1).copy()
Y_train=train_df["Price"]
Y_test=test_df["Price"]

In [98]:
X_test

,S.No.,Location,Year,Kilometers_Driven,Engine,Power,Seats,Engine_CC,Power_bhp,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
4852,4852,Chennai,2010,107389,1399 CC,68 bhp,5.0,1399.0,68.00,0,1,0,0,0,0,1,0,0,1,0
4519,4519,Mumbai,2008,46810,1995 CC,163.5 bhp,5.0,1995.0,163.50,0,0,0,0,1,0,1,1,0,0,0
4126,4126,Pune,2011,97000,1968 CC,138.08 bhp,5.0,1968.0,138.08,0,1,0,0,0,0,1,1,0,0,0
5496,5496,Delhi,2016,22129,1197 CC,82 bhp,5.0,1197.0,82.00,0,0,0,0,1,0,1,1,0,0,0
5983,5983,Kolkata,2011,55001,1198 CC,73.9 bhp,5.0,1198.0,73.90,0,0,0,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6409,6409,Ahmedabad,2016,67000,1248 CC,74 bhp,5.0,1248.0,74.00,0,1,0,0,0,0,1,1,0,0,0
5714,5714,Mumbai,2010,57000,1197 CC,78.9 bhp,5.0,1197.0,78.90,0,0,0,0,1,1,0,0,0,1,0
5362,5362,Bangalore,2014,29063,1968 CC,174.33 bhp,5.0,1968.0,174.33,0,1,0,0,0,1,0,1,0,0,0
615,615,Hyderabad,2017,52000,2393 CC,147.8 bhp,8.0,2393.0,147.80,0,1,0,0,0,0,1,1,0,0,0
1561,1561,Pune,2017,38767,1582 CC,126.2 bhp,5.0,1582.0,126.20,0,1,0,0,0,0,1,1,0,0,0

In [99]:
X_train

,S.No.,Location,Year,Kilometers_Driven,Engine,Power,Seats,Engine_CC,Power_bhp,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
4217,4217,Ahmedabad,2014,75000,1498 CC,98.6 bhp,5.0,1498.0,98.60,0,1,0,0,0,0,1,1,0,0,0
811,811,Chennai,2015,65000,1498 CC,98.6 bhp,7.0,1498.0,98.60,0,1,0,0,0,0,1,1,0,0,0
1538,1538,Chennai,2015,21000,796 CC,47.3 bhp,5.0,796.0,47.30,0,0,0,0,1,0,1,1,0,0,0
5981,5981,Mumbai,2017,6000,1197 CC,83.1 bhp,5.0,1197.0,83.10,0,0,0,0,1,0,1,1,0,0,0
1534,1534,Coimbatore,2019,23882,1497 CC,117.3 bhp,5.0,1497.0,117.30,0,0,0,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4399,4399,Chennai,2019,65000,1248 CC,74 bhp,5.0,1248.0,74.00,0,1,0,0,0,1,0,1,0,0,0
1816,1816,Kochi,2019,27339,1197 CC,81.83 bhp,5.0,1197.0,81.83,0,0,0,0,1,0,1,1,0,0,0
533,533,Mumbai,2010,69000,1497 CC,118 bhp,5.0,1497.0,118.00,0,0,0,0,1,1,0,0,0,1,0
4013,4013,Jaipur,2017,40000,2179 CC,140 bhp,7.0,2179.0,140.00,0,1,0,0,0,0,1,1,0,0,0
409,409,Kochi,2017,37542,1968 CC,174.33 bhp,5.0,1968.0,174.33,0,1,0,0,0,1,0,1,0,0,0

In [100]:
Y_train.head()

4217     6.00
811      5.50
1538     2.79
5981     7.50
1534    11.87
Name: Price, dtype: float64

In [105]:
df

,S.No.,Location,Year,Kilometers_Driven,Engine,Power,Seats,Price,Engine_CC,Power_bhp,...,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Mumbai,2010,72000,998 CC,58.16 bhp,5.0,1.750000,998.0,58.16,...,0,0,0,0,0,1,1,0,0,0
1,1,Pune,2015,41000,1582 CC,126.2 bhp,5.0,12.500000,1582.0,126.20,...,1,0,0,0,0,1,1,0,0,0
2,2,Chennai,2011,46000,1199 CC,88.7 bhp,5.0,4.500000,1199.0,88.70,...,0,0,0,1,0,1,1,0,0,0
3,3,Chennai,2012,87000,1248 CC,88.76 bhp,7.0,6.000000,1248.0,88.76,...,1,0,0,0,0,1,1,0,0,0
4,4,Coimbatore,2013,40670,1968 CC,140.8 bhp,5.0,17.740000,1968.0,140.80,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Hyderabad,2011,89411,1598 CC,103.6 bhp,5.0,9.479468,1598.0,103.60,...,1,0,0,0,0,1,1,0,0,0
7249,7249,Mumbai,2015,59000,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,...,0,0,0,1,1,0,1,0,0,0
7250,7250,Kolkata,2012,28000,1461 CC,63.1 bhp,5.0,9.479468,1461.0,63.10,...,1,0,0,0,0,1,1,0,0,0
7251,7251,Pune,2013,52262,1197 CC,103.6 bhp,5.0,9.479468,1197.0,103.60,...,0,0,0,1,1,0,0,0,0,1
7252,7252,Kochi,2014,72443,2148 CC,170 bhp,5.0,9.479468,2148.0,170.00,...,1,0,0,0,1,0,1,0,0,0

In [77]:
X_train.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Engine_CC,Power_bhp
2930,2930,Nissan Micra Diesel XV,Hyderabad,2011,123880,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,1461.0,63.10
4291,4291,Skoda Laura Ambiente 2.0 TDI CR AT,Jaipur,2011,115692,Diesel,Automatic,First,1968 CC,138.1 bhp,5.0,1968.0,138.10
4851,4851,Chevrolet Spark 1.0 LT,Chennai,2011,29000,Petrol,Manual,Second,995 CC,62 bhp,5.0,995.0,62.00
5419,5419,Toyota Corolla Altis 1.8 VL CVT,Coimbatore,2016,82725,Petrol,Automatic,First,1798 CC,138.03 bhp,5.0,1798.0,138.03
1956,1956,Hyundai i20 1.4 CRDi Magna,Hyderabad,2011,75000,Diesel,Manual,First,1396 CC,90 bhp,5.0,1396.0,90.00

In [116]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ["Location"]:
    df[Location] = le.fit_transform(df[Location])

NameError: name 'Location' is not defined

In [115]:

model = LinearRegression()

model.fit(X_train, Y_train)

prediction = model.predict(X_test)

ValueError: could not convert string to float: 'Ahmedabad'