In [68]:
import pandas as pd
import numpy as np
import matmean_squared_errorplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.linear_model import LinearRegression
from sklearn.metrics import

In [99]:
df=pd.DataFrame(pd.read_csv(r"used_cars_data.csv"))

In [100]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [28]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74

In [29]:
df.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,9.479468
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,9.479468
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,9.479468
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,9.479468
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,9.479468

In [30]:
df.describe()

             S.No.         Year  Kilometers_Driven        Seats        Price
count  7253.000000  7253.000000       7.253000e+03  7200.000000  7253.000000
mean   3626.000000  2013.365366       5.869906e+04     5.279722     9.479468
std    2093.905084     3.254421       8.442772e+04     0.811660    10.191695
min       0.000000  1996.000000       1.710000e+02     0.000000     0.440000
25%    1813.000000  2011.000000       3.400000e+04     5.000000     3.850000
50%    3626.000000  2014.000000       5.341600e+04     5.000000     6.750000
75%    5439.000000  2016.000000       7.300000e+04     5.000000     9.479468
max    7252.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [31]:
df.isnull().sum()

S.No.                 0
Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               46
Power                46
Seats                53
Price                 0
dtype: int64

In [32]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7248    False
7249    False
7250    False
7251    False
7252    False
Length: 7253, dtype: bool

In [33]:
df.shape

(7253, 13)

In [101]:
df
df.drop("Mileage",axis=1,inplace=True)

In [102]:
df["Price"]=df["Price"].fillna(df["Price"].mean())

In [103]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,998 CC,58.16 bhp,5.0,NaN,1.750000
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1582 CC,126.2 bhp,5.0,NaN,12.500000
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.500000
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,1248 CC,88.76 bhp,7.0,NaN,6.000000
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,140.8 bhp,5.0,NaN,17.740000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,NaN,9.479468
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,NaN,9.479468
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,NaN,9.479468
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,NaN,9.479468
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,NaN,9.479468

In [104]:
df["Engine_CC"] = df["Engine"].str.split().str[0].astype(float)
df["Engine_CC"] = df["Engine_CC"].fillna(df["Engine_CC"].mean())

In [105]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,New_Price,Price,Engine_CC
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,998 CC,58.16 bhp,5.0,NaN,1.750000,998.0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1582 CC,126.2 bhp,5.0,NaN,12.500000,1582.0
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.500000,1199.0
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,1248 CC,88.76 bhp,7.0,NaN,6.000000,1248.0
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,140.8 bhp,5.0,NaN,17.740000,1968.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,NaN,9.479468,1598.0
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,NaN,9.479468,1197.0
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,NaN,9.479468,1461.0
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,NaN,9.479468,1197.0
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,NaN,9.479468,2148.0

In [106]:
df["Power_bhp"] = ( df["Power"].str.split().str[0].replace("null", np.nan).astype(float))
df["Power_bhp"] = df["Power_bhp"].fillna(df["Power_bhp"].mean())

In [89]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Engine,Power,Seats,Price,Engine_CC,...,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,998 CC,58.16 bhp,5.0,1.750000,998.0,...,0,0,0,0,0,1,1,0,0,0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,1582 CC,126.2 bhp,5.0,12.500000,1582.0,...,1,0,0,0,0,1,1,0,0,0
2,2,Honda Jazz V,Chennai,2011,46000,1199 CC,88.7 bhp,5.0,4.500000,1199.0,...,0,0,0,1,0,1,1,0,0,0
3,3,Maruti Ertiga VDI,Chennai,2012,87000,1248 CC,88.76 bhp,7.0,6.000000,1248.0,...,1,0,0,0,0,1,1,0,0,0
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,1968 CC,140.8 bhp,5.0,17.740000,1968.0,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,1598 CC,103.6 bhp,5.0,9.479468,1598.0,...,1,0,0,0,0,1,1,0,0,0
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,1197 CC,103.6 bhp,5.0,9.479468,1197.0,...,0,0,0,1,1,0,1,0,0,0
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,1461 CC,63.1 bhp,5.0,9.479468,1461.0,...,1,0,0,0,0,1,1,0,0,0
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,1197 CC,103.6 bhp,5.0,9.479468,1197.0,...,0,0,0,1,1,0,0,0,0,1
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,2148 CC,170 bhp,5.0,9.479468,2148.0,...,1,0,0,0,1,0,1,0,0,0

In [107]:
df.loc[df["Seats"]<5,"Seats"]=5
df["Seats"] = df["Seats"].fillna(5)

In [91]:
df.isnull().sum()

S.No.                         0
Name                          0
Location                      0
Year                          0
Kilometers_Driven             0
Engine                       46
Power                        46
Seats                         0
Price                         0
Engine_CC                     0
Power_bhp                     0
Fuel_Type_CNG                 0
Fuel_Type_Diesel              0
Fuel_Type_Electric            0
Fuel_Type_LPG                 0
Fuel_Type_Petrol              0
Transmission_Automatic        0
Transmission_Manual           0
Owner_Type_First              0
Owner_Type_Fourth & Above     0
Owner_Type_Second             0
Owner_Type_Third              0
dtype: int64

In [92]:
df.describe()

,S.No.,Year,Kilometers_Driven,Seats,Price,Engine_CC,Power_bhp,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
count,7253.000000,7253.000000,7.253000e+03,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000
mean,3626.000000,2013.365366,5.869906e+04,5.302220,9.479468,1616.573470,112.765214,0.008548,0.531091,0.000276,0.001654,0.458431,0.282504,0.717496,0.820626,0.001654,0.158831,0.018889
std,2093.905084,3.254421,8.442772e+04,0.773379,10.191695,593.394164,52.844178,0.092067,0.499067,0.016605,0.040645,0.498303,0.450248,0.450248,0.383692,0.040645,0.365543,0.136141
min,0.000000,1996.000000,1.710000e+02,5.000000,0.440000,72.000000,34.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1813.000000,2011.000000,3.400000e+04,5.000000,3.850000,1198.000000,77.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,3626.000000,2014.000000,5.341600e+04,5.000000,6.750000,1493.000000,98.600000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,5439.000000,2016.000000,7.300000e+04,5.000000,9.479468,1968.000000,138.030000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
max,7252.000000,2019.000000,6.500000e+06,10.000000,160.000000,5998.000000,616.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [108]:
df = pd.get_dummies(df,columns=["Fuel_Type", "Transmission", "Owner_Type"],dtype=int)

In [94]:
df

,S.No.,Name,Location,Year,Kilometers_Driven,Engine,Power,Seats,Price,Engine_CC,...,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,998 CC,58.16 bhp,5.0,1.750000,998.0,...,0,0,0,0,0,1,1,0,0,0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,1582 CC,126.2 bhp,5.0,12.500000,1582.0,...,1,0,0,0,0,1,1,0,0,0
2,2,Honda Jazz V,Chennai,2011,46000,1199 CC,88.7 bhp,5.0,4.500000,1199.0,...,0,0,0,1,0,1,1,0,0,0
3,3,Maruti Ertiga VDI,Chennai,2012,87000,1248 CC,88.76 bhp,7.0,6.000000,1248.0,...,1,0,0,0,0,1,1,0,0,0
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,1968 CC,140.8 bhp,5.0,17.740000,1968.0,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,1598 CC,103.6 bhp,5.0,9.479468,1598.0,...,1,0,0,0,0,1,1,0,0,0
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,1197 CC,103.6 bhp,5.0,9.479468,1197.0,...,0,0,0,1,1,0,1,0,0,0
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,1461 CC,63.1 bhp,5.0,9.479468,1461.0,...,1,0,0,0,0,1,1,0,0,0
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,1197 CC,103.6 bhp,5.0,9.479468,1197.0,...,0,0,0,1,1,0,0,0,0,1
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,2148 CC,170 bhp,5.0,9.479468,2148.0,...,1,0,0,0,1,0,1,0,0,0

In [132]:
scaler = StandardScaler()

In [133]:
df["Kilometers_Driven"]=scaler.fit_transform(df[["Kilometers_Driven"]])

In [134]:
scaler2 = StandardScaler()

In [136]:
df["Price"]=scaler2.fit_transform(df[["Price"]])

In [137]:
X_test

NameError: name 'X_test' is not defined